version: "3.9"

services:
  gofindpi:
    build:
      context: .
      dockerfile: Dockerfile
    image: gofindpi:latest
    container_name: gofindpi
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: "no"